-- =============================================================================
-- FlossWing State Schema
-- =============================================================================
--
-- This file is the canonical schema reference. It is NOT applied directly.
-- The actual schema is created by Alembic migrations in
-- `flosswing/state/migrations/versions/`. This file MUST stay in sync with the
-- result of `alembic upgrade head` against an empty database.
--
-- Sync check: `tests/unit/test_schema_sync.py` runs `alembic upgrade head`
-- against a temp SQLite DB, builds a second temp DB by executing this file, and
-- compares them *structurally* via PRAGMA introspection (columns incl. position,
-- foreign keys, indexes, and CHECK/UNIQUE/FK/PK constraint names) — not a text
-- dump, so formatting and clause ordering are ignored. Drift fails the build.
--
-- --- Alembic conventions for FlossWing ---------------------------------------
--
--   env.py MUST set:
--       context.configure(
--           connection=connection,
--           target_metadata=target_metadata,
--           render_as_batch=True,           # SQLite ALTER TABLE workaround
--           compare_type=True,              # detect type changes in autogenerate
--           compare_server_default=True,
--       )
--
--   Every constraint MUST be named. SQLite allows anonymous constraints;
--   Alembic's batch mode cannot drop or alter them. Use this naming convention
--   (set via SQLAlchemy naming_convention on the MetaData):
--
--       "ix":  "ix_%(table_name)s_%(column_0_name)s"
--       "uq":  "uq_%(table_name)s_%(column_0_name)s"
--       "ck":  "ck_%(table_name)s_%(constraint_name)s"
--       "fk":  "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s"
--       "pk":  "pk_%(table_name)s"
--
--   Foreign keys ARE enforced. The state-store init code MUST run
--   `PRAGMA foreign_keys = ON` on every new connection (SQLite default is OFF).
--   Alembic's batch_alter_table will disable FKs during a table copy and
--   re-enable them after; that's expected.
--
--   Autogenerate WILL produce wrong migrations for SQLite in some cases
--   (CHECK constraints, column-type narrowing). Every autogenerated migration
--   MUST be reviewed by the operator before being committed. Claude Code is
--   instructed in CLAUDE.md to never commit an autogenerated migration without
--   showing the diff and waiting for approval.
--
-- --- Conventions used in this schema -----------------------------------------
--
--   IDs:        TEXT (ULID, generated at insert time by the application).
--               ULIDs are sortable by creation time, which simplifies most
--               queries that want "recent first" without a separate timestamp.
--   Timestamps: TEXT in ISO-8601 UTC ('2026-05-25T17:00:00Z'). SQLite has no
--               real datetime type; we use TEXT with a strict format and
--               normalize at the application layer. INTEGER unix epoch was
--               considered but TEXT survives raw inspection ("sqlite3 state.db"
--               .schema and SELECT) far better.
--   JSON:       TEXT, with a CHECK(json_valid(...)) constraint. SQLite has
--               JSON1 builtin since 3.38; we require >=3.38 (Python 3.11 ships
--               3.40+, no realistic compatibility concern).
--   Enums:      TEXT with CHECK(col IN (...)) constraints. Mirrors the
--               Literal[] types in docs/tool-contracts.md exactly. Keep these
--               two in sync; the CI schema-check catches drift.
--   Booleans:   INTEGER 0/1. SQLite stores them as INTEGER regardless of
--               declared type, so we're explicit.
--
-- =============================================================================


-- -----------------------------------------------------------------------------
-- runs: one row per `flosswing scan` invocation.
-- -----------------------------------------------------------------------------
--
-- A run is the unit of work users reason about. Everything else hangs off a
-- run via FK. Deleting a run cascades to all its findings, tasks, sessions,
-- etc. — there's no archival mode in v1; if a user wants to keep findings
-- they export them.

CREATE TABLE runs (
    id                  TEXT NOT NULL,                   -- ULID
    target_repo_path    TEXT NOT NULL,                   -- absolute path at scan time (informational)
    target_repo_sha     TEXT,                            -- git HEAD at scan time, if available; NULL for non-git repos
    depth               TEXT NOT NULL,                   -- 'quick' | 'standard' | 'deep'
    budget_total        INTEGER NOT NULL,                -- total Hunt-task budget
    budget_used         INTEGER NOT NULL DEFAULT 0,
    started_at          TEXT NOT NULL,                   -- ISO-8601 UTC
    finished_at         TEXT,                            -- NULL while running
    status              TEXT NOT NULL DEFAULT 'running', -- 'running' | 'completed' | 'errored' | 'aborted'
    config_json         TEXT NOT NULL,                   -- full resolved config (CLI + env + files), JSON
    flosswing_version   TEXT NOT NULL,                   -- e.g. '0.3.1' — for forward-compat of old runs

    CONSTRAINT pk_runs PRIMARY KEY (id),
    CONSTRAINT ck_runs_depth CHECK (depth IN ('quick', 'standard', 'deep')),
    CONSTRAINT ck_runs_status CHECK (status IN ('running', 'completed', 'errored', 'aborted')),
    CONSTRAINT ck_runs_budget CHECK (budget_total >= 0 AND budget_used >= 0),
    CONSTRAINT ck_runs_config_json_valid CHECK (json_valid(config_json))
);

CREATE INDEX ix_runs_started_at ON runs(started_at);
CREATE INDEX ix_runs_status ON runs(status);


-- -----------------------------------------------------------------------------
-- recon_artifacts: Recon stage output, one per run.
-- -----------------------------------------------------------------------------
--
-- 1:1 with runs in v1 (Recon runs once per scan). Split into its own table
-- rather than columns on `runs` because (a) the JSON blobs are large and we
-- don't want them on every `SELECT * FROM runs`, and (b) it gives entry_points,
-- subsystems, etc. a stable identity for FK targets (see entry_points below).
--
-- recon_artifact_id is also the FK target for hunt_tasks created during Recon.

CREATE TABLE recon_artifacts (
    id                  TEXT NOT NULL,                   -- ULID
    run_id              TEXT NOT NULL,
    languages_json      TEXT NOT NULL,                   -- JSON array of detected languages
    build_commands_json TEXT NOT NULL,                   -- JSON object: {"primary": "make", ...}
    trust_boundaries_json TEXT NOT NULL,                 -- JSON array of TrustBoundary
    subsystems_json     TEXT NOT NULL,                   -- JSON array of Subsystem
    notes               TEXT NOT NULL DEFAULT '',
    recorded_at         TEXT NOT NULL,

    CONSTRAINT pk_recon_artifacts PRIMARY KEY (id),
    CONSTRAINT fk_recon_artifacts_run_id_runs FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
    CONSTRAINT uq_recon_artifacts_run_id UNIQUE (run_id),  -- one artifact per run
    CONSTRAINT ck_recon_artifacts_languages_valid CHECK (json_valid(languages_json)),
    CONSTRAINT ck_recon_artifacts_builds_valid CHECK (json_valid(build_commands_json)),
    CONSTRAINT ck_recon_artifacts_trust_valid CHECK (json_valid(trust_boundaries_json)),
    CONSTRAINT ck_recon_artifacts_subsystems_valid CHECK (json_valid(subsystems_json))
);


-- -----------------------------------------------------------------------------
-- entry_points: identified by Recon, queried by Trace.
-- -----------------------------------------------------------------------------
--
-- Stored as a proper table (not just JSON in recon_artifacts) because:
--   - Trace queries them by kind: SELECT WHERE kind = 'http'
--   - Future Trace stages may want to FK against a specific entry point
--   - They participate in the symbol index lookup path
--
-- Note that the "symbol" here is the fully-qualified name as emitted by
-- tree-sitter's parser for the relevant language. The symbols table (below)
-- has the canonical resolution.

CREATE TABLE entry_points (
    id                  TEXT NOT NULL,                   -- ULID
    recon_artifact_id   TEXT NOT NULL,
    run_id              TEXT NOT NULL,                   -- denormalized for query convenience
    symbol              TEXT NOT NULL,
    file                TEXT NOT NULL,                   -- repo-relative POSIX path
    line                INTEGER NOT NULL,
    kind                TEXT NOT NULL,                   -- 'http' | 'cli' | 'exported' | 'deserializer' | 'ipc'
    attacker_controlled_input INTEGER NOT NULL,          -- 0 | 1
    notes               TEXT NOT NULL DEFAULT '',

    CONSTRAINT pk_entry_points PRIMARY KEY (id),
    CONSTRAINT fk_entry_points_recon_artifact_id_recon_artifacts
        FOREIGN KEY (recon_artifact_id) REFERENCES recon_artifacts(id) ON DELETE CASCADE,
    CONSTRAINT fk_entry_points_run_id_runs
        FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
    CONSTRAINT ck_entry_points_kind
        CHECK (kind IN ('http', 'cli', 'exported', 'deserializer', 'ipc')),
    CONSTRAINT ck_entry_points_attacker_input
        CHECK (attacker_controlled_input IN (0, 1)),
    CONSTRAINT ck_entry_points_line CHECK (line >= 1)
);

CREATE INDEX ix_entry_points_run_id ON entry_points(run_id);
CREATE INDEX ix_entry_points_kind ON entry_points(kind);


-- -----------------------------------------------------------------------------
-- symbols: tree-sitter symbol index, populated by Recon.
-- -----------------------------------------------------------------------------
--
-- This is the index `find_definition` and `find_callers` query against. Built
-- once per run during Recon's pre-agent setup.
--
-- Trade-off note: we COULD scope symbols globally (cross-run) and rebuild
-- incrementally. Decision: scope per-run. Reasons:
--   - simpler invalidation (delete run -> symbols go away)
--   - cross-repo trace is a deferred v2 feature
--   - tree-sitter parsing is fast enough that rebuild-per-scan is fine
-- If/when we add `flosswing diff <run_a> <run_b>`, we'll join across runs;
-- the (run_id, file, line_start) composite query is cheap.

CREATE TABLE symbols (
    id                  TEXT NOT NULL,                   -- ULID
    run_id              TEXT NOT NULL,
    symbol              TEXT NOT NULL,                   -- short name, e.g. "run_user_cmd"
    fully_qualified_name TEXT NOT NULL,                  -- e.g. "pkg.subpkg.module.Class.method"
    file                TEXT NOT NULL,
    line_start          INTEGER NOT NULL,
    line_end            INTEGER NOT NULL,
    kind                TEXT NOT NULL,
    language            TEXT NOT NULL,

    CONSTRAINT pk_symbols PRIMARY KEY (id),
    CONSTRAINT fk_symbols_run_id_runs FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
    CONSTRAINT ck_symbols_kind
        CHECK (kind IN ('function', 'method', 'class', 'struct', 'enum', 'macro', 'type')),
    CONSTRAINT ck_symbols_lines
        CHECK (line_start >= 1 AND line_end >= line_start)
);

-- Hot query path: find_definition(symbol, file_hint?, language?)
CREATE INDEX ix_symbols_run_id_symbol ON symbols(run_id, symbol);
CREATE INDEX ix_symbols_run_id_fqn ON symbols(run_id, fully_qualified_name);
CREATE INDEX ix_symbols_run_id_file ON symbols(run_id, file);


-- -----------------------------------------------------------------------------
-- call_sites: who calls whom, populated by Recon alongside symbols.
-- -----------------------------------------------------------------------------
--
-- Separate table from `symbols` because the cardinality is much higher (many
-- call sites per symbol). Backed by tree-sitter's call expression extraction.
-- Imperfect for highly dynamic languages (Python `getattr`, JS `[]`-indexed
-- calls, reflection in Java/Go); we accept the imperfection and mark traces
-- using such constructs as `uncertain`.
--
-- callee_symbol_id is nullable: if the called symbol couldn't be resolved
-- against `symbols` (e.g. it's in a third-party library), we still record the
-- call site with the unresolved name in callee_text for grep-based fallback
-- in Trace.

CREATE TABLE call_sites (
    id                  TEXT NOT NULL,                   -- ULID
    run_id              TEXT NOT NULL,
    caller_symbol_id    TEXT NOT NULL,
    callee_symbol_id    TEXT,                            -- NULL if unresolved
    callee_text         TEXT NOT NULL,                   -- raw text of the call target as written
    file                TEXT NOT NULL,
    line                INTEGER NOT NULL,
    snippet             TEXT NOT NULL,                   -- the line(s), truncated

    CONSTRAINT pk_call_sites PRIMARY KEY (id),
    CONSTRAINT fk_call_sites_run_id_runs
        FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
    CONSTRAINT fk_call_sites_caller_symbols
        FOREIGN KEY (caller_symbol_id) REFERENCES symbols(id) ON DELETE CASCADE,
    CONSTRAINT fk_call_sites_callee_symbols
        FOREIGN KEY (callee_symbol_id) REFERENCES symbols(id) ON DELETE SET NULL,
    CONSTRAINT ck_call_sites_line CHECK (line >= 1)
);

-- Hot query: find_callers(symbol) => WHERE callee_symbol_id = ?
CREATE INDEX ix_call_sites_run_id_callee ON call_sites(run_id, callee_symbol_id);
CREATE INDEX ix_call_sites_run_id_caller ON call_sites(run_id, caller_symbol_id);
-- Fallback for unresolved callees: WHERE callee_text = ? AND callee_symbol_id IS NULL
CREATE INDEX ix_call_sites_run_id_callee_text ON call_sites(run_id, callee_text);


-- -----------------------------------------------------------------------------
-- hunt_tasks: one Hunt-stage task per (attack_class, scope).
-- -----------------------------------------------------------------------------
--
-- Created by Recon (initial population) and Gapfill (additions). Consumed by
-- the Hunt orchestrator. Status transitions are append-only via started_at /
-- finished_at — we don't track intermediate states, just the terminal one.

CREATE TABLE hunt_tasks (
    id                  TEXT NOT NULL,                   -- ULID
    run_id              TEXT NOT NULL,
    attack_class        TEXT NOT NULL,                   -- validated against registry at insert time
    scope_hint          TEXT NOT NULL,
    rationale           TEXT NOT NULL DEFAULT '',        -- why this task was created
    priority            TEXT NOT NULL DEFAULT 'normal',  -- 'high' | 'normal' | 'low'
    source              TEXT NOT NULL,                   -- 'recon' | 'gapfill'
    parent_finding_id   TEXT,                            -- set by Gapfill when re-queueing around a finding
    status              TEXT NOT NULL DEFAULT 'pending', -- see CHECK below
    created_at          TEXT NOT NULL,
    started_at          TEXT,
    finished_at         TEXT,
    findings_count      INTEGER NOT NULL DEFAULT 0,      -- denormalized cache, updated on record_finding

    CONSTRAINT pk_hunt_tasks PRIMARY KEY (id),
    CONSTRAINT fk_hunt_tasks_run_id_runs
        FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
    -- parent_finding_id intentionally NOT FK'd: Gapfill may create tasks
    -- referencing findings that haven't been recorded yet (race window during
    -- parallel writes). We validate at the application layer instead.
    CONSTRAINT ck_hunt_tasks_priority
        CHECK (priority IN ('high', 'normal', 'low')),
    CONSTRAINT ck_hunt_tasks_source
        CHECK (source IN ('recon', 'gapfill')),
    CONSTRAINT ck_hunt_tasks_status
        CHECK (status IN ('pending', 'running', 'completed', 'refused', 'budget_exceeded', 'errored')),
    CONSTRAINT ck_hunt_tasks_findings_count CHECK (findings_count >= 0)
);

-- Queue dequeue query: WHERE run_id = ? AND status = 'pending' ORDER BY priority, created_at
CREATE INDEX ix_hunt_tasks_run_id_status ON hunt_tasks(run_id, status);
CREATE INDEX ix_hunt_tasks_attack_class ON hunt_tasks(attack_class);


-- -----------------------------------------------------------------------------
-- findings: the primary artifact of a scan.
-- -----------------------------------------------------------------------------
--
-- Created by Hunt (`record_finding`). Mutated by Validate (sets `status` and
-- `validated_at` via the validations table) and by Dedupe (sets
-- `primary_finding_id` and `dedupe_role`).
--
-- poc_result_json is the full ExecResult from compile_and_run, stored verbatim
-- so the report can show stdout/stderr/exit code etc. without re-execution.
-- Size cap enforced at the application layer (we cap each ExecResult's
-- stdout/stderr in compile_and_run; row size stays manageable).

CREATE TABLE findings (
    id                  TEXT NOT NULL,                   -- ULID
    run_id              TEXT NOT NULL,
    hunt_task_id        TEXT NOT NULL,
    attack_class        TEXT NOT NULL,
    file                TEXT NOT NULL,
    function            TEXT,                            -- may be NULL if Hunter couldn't identify the containing fn
    line_start          INTEGER NOT NULL,
    line_end            INTEGER NOT NULL,
    severity            TEXT NOT NULL,                   -- 'critical' | 'high' | 'medium' | 'low' | 'info'
    confidence          TEXT NOT NULL,                   -- 'confirmed' | 'likely' | 'speculative'
    status              TEXT NOT NULL DEFAULT 'pending_validation',
    -- status transitions:
    --   pending_validation -> confirmed | rejected | uncertain  (set by Validate)
    --   any -> superseded                                       (set by Dedupe merge)
    title               TEXT NOT NULL,                   -- one-line summary, ≤120 chars (app-enforced)
    description         TEXT NOT NULL,                   -- markdown
    poc_code            TEXT,                            -- the PoC source, if Hunter ran one
    poc_result_json     TEXT,                            -- full CompileAndRunOutput JSON, if any
    suggested_fix       TEXT,                            -- markdown, optional

    -- Dedupe-managed:
    primary_finding_id  TEXT,                            -- if this is a duplicate, points at the primary
    dedupe_cluster_id   TEXT,                            -- cluster membership (see dedupe_clusters)
    dedupe_role         TEXT,                            -- 'primary' | 'variant' | 'duplicate' | NULL
    root_cause_summary  TEXT,                            -- set on the primary when a cluster is merged

    -- Trace-managed (also see traces table for full call chain):
    reachable           TEXT,                            -- 'reachable' | 'unreachable' | 'uncertain' | NULL

    created_at          TEXT NOT NULL,
    validated_at        TEXT,
    superseded_at       TEXT,                            -- set when merged into a primary

    CONSTRAINT pk_findings PRIMARY KEY (id),
    CONSTRAINT fk_findings_run_id_runs
        FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
    CONSTRAINT fk_findings_hunt_task_id_hunt_tasks
        FOREIGN KEY (hunt_task_id) REFERENCES hunt_tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_findings_primary_findings
        FOREIGN KEY (primary_finding_id) REFERENCES findings(id) ON DELETE SET NULL,
    CONSTRAINT fk_findings_dedupe_cluster_id_dedupe_clusters
        FOREIGN KEY (dedupe_cluster_id) REFERENCES dedupe_clusters(id)
        ON DELETE SET NULL,
    CONSTRAINT ck_findings_severity
        CHECK (severity IN ('critical', 'high', 'medium', 'low', 'info')),
    CONSTRAINT ck_findings_confidence
        CHECK (confidence IN ('confirmed', 'likely', 'speculative')),
    CONSTRAINT ck_findings_status
        CHECK (status IN ('pending_validation', 'confirmed', 'rejected', 'uncertain', 'superseded')),
    CONSTRAINT ck_findings_dedupe_role
        CHECK (dedupe_role IS NULL OR dedupe_role IN ('primary', 'variant', 'duplicate')),
    CONSTRAINT ck_findings_reachable
        CHECK (reachable IS NULL OR reachable IN ('reachable', 'unreachable', 'uncertain')),
    CONSTRAINT ck_findings_lines CHECK (line_start >= 1 AND line_end >= line_start),
    CONSTRAINT ck_findings_poc_result_valid
        CHECK (poc_result_json IS NULL OR json_valid(poc_result_json)),
    -- Confirmed findings must have either a PoC OR a trace as evidence.
    -- We can't easily check "has trace" here without a JOIN; we relax to
    -- "either has poc OR description is non-trivial". The tool layer enforces
    -- the stronger invariant. This CHECK catches manual SQL surgery only.
    CONSTRAINT ck_findings_confirmed_evidence
        CHECK (confidence != 'confirmed' OR length(description) >= 50)
);

CREATE INDEX ix_findings_run_id_status ON findings(run_id, status);
CREATE INDEX ix_findings_run_id_severity ON findings(run_id, severity);
CREATE INDEX ix_findings_attack_class ON findings(attack_class);
CREATE INDEX ix_findings_file ON findings(file);
CREATE INDEX ix_findings_primary_finding_id ON findings(primary_finding_id);
CREATE INDEX ix_findings_dedupe_cluster_id ON findings(dedupe_cluster_id);


-- -----------------------------------------------------------------------------
-- validations: adversarial review records.
-- -----------------------------------------------------------------------------
--
-- One per (finding, validation pass). v1 has exactly one validation pass per
-- finding (sealed after the first verdict), but the table is structured to
-- allow multiple in v2 if we add "re-validate after fix" workflows. The UNIQUE
-- constraint enforces the v1 invariant.

CREATE TABLE validations (
    id                  TEXT NOT NULL,                   -- ULID
    finding_id          TEXT NOT NULL,
    verdict             TEXT NOT NULL,                   -- 'confirmed' | 'rejected' | 'uncertain'
    rationale           TEXT NOT NULL,                   -- markdown, ≥50 chars (app-enforced)
    evidence_files_json TEXT NOT NULL DEFAULT '[]',      -- JSON array of paths examined
    agent_session_id    TEXT NOT NULL,                   -- traceability to the LLM session
    created_at          TEXT NOT NULL,

    CONSTRAINT pk_validations PRIMARY KEY (id),
    CONSTRAINT fk_validations_finding_id_findings
        FOREIGN KEY (finding_id) REFERENCES findings(id) ON DELETE CASCADE,
    CONSTRAINT fk_validations_agent_session_id_agent_sessions
        FOREIGN KEY (agent_session_id) REFERENCES agent_sessions(id) ON DELETE RESTRICT,
    CONSTRAINT uq_validations_finding_id UNIQUE (finding_id),  -- v1: one validation per finding
    CONSTRAINT ck_validations_verdict
        CHECK (verdict IN ('confirmed', 'rejected', 'uncertain')),
    CONSTRAINT ck_validations_evidence_valid CHECK (json_valid(evidence_files_json))
);


-- -----------------------------------------------------------------------------
-- dedupe_clusters: groups of findings sharing a root cause.
-- -----------------------------------------------------------------------------
--
-- Created by the Dedupe stage. Each cluster has one primary finding (the
-- canonical one operators should look at) and zero or more variants/duplicates
-- linked via findings.primary_finding_id.
--
-- The cluster row exists separately from the primary finding so that:
--   1. The root_cause_summary lives on the cluster, not denormalized onto
--      every member finding (it WAS on findings.root_cause_summary above for
--      the primary; that's a denormalization for query convenience, and the
--      cluster row is the source of truth).
--   2. Future variants can be added without modifying the primary.

CREATE TABLE dedupe_clusters (
    id                  TEXT NOT NULL,                   -- ULID
    run_id              TEXT NOT NULL,
    primary_finding_id  TEXT NOT NULL,
    root_cause_summary  TEXT NOT NULL,                   -- markdown
    created_at          TEXT NOT NULL,
    member_count        INTEGER NOT NULL,                -- denormalized; updated on merge

    CONSTRAINT pk_dedupe_clusters PRIMARY KEY (id),
    CONSTRAINT fk_dedupe_clusters_run_id_runs
        FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
    CONSTRAINT fk_dedupe_clusters_primary_findings
        FOREIGN KEY (primary_finding_id) REFERENCES findings(id) ON DELETE CASCADE,
    CONSTRAINT ck_dedupe_clusters_member_count CHECK (member_count >= 1)
);

CREATE INDEX ix_dedupe_clusters_run_id ON dedupe_clusters(run_id);


-- -----------------------------------------------------------------------------
-- finding_links: non-merge relationships between findings.
-- -----------------------------------------------------------------------------
--
-- For `link_variant` operations that mark two findings as related without
-- collapsing them. Distinct from dedupe_clusters which DOES collapse.
--
-- Symmetric in semantics but stored as directed pairs (a -> b). Application
-- treats lookup as bidirectional via UNION on both columns.

CREATE TABLE finding_links (
    id                  TEXT NOT NULL,                   -- ULID
    finding_id_a        TEXT NOT NULL,
    finding_id_b        TEXT NOT NULL,
    relationship        TEXT NOT NULL,
    note                TEXT NOT NULL DEFAULT '',
    created_at          TEXT NOT NULL,

    CONSTRAINT pk_finding_links PRIMARY KEY (id),
    CONSTRAINT fk_finding_links_a_findings
        FOREIGN KEY (finding_id_a) REFERENCES findings(id) ON DELETE CASCADE,
    CONSTRAINT fk_finding_links_b_findings
        FOREIGN KEY (finding_id_b) REFERENCES findings(id) ON DELETE CASCADE,
    CONSTRAINT ck_finding_links_relationship
        CHECK (relationship IN ('same_root_cause', 'exploit_chain', 'preconditions')),
    CONSTRAINT ck_finding_links_distinct CHECK (finding_id_a != finding_id_b),
    -- Prevent duplicate links in either direction:
    CONSTRAINT uq_finding_links_ordered UNIQUE (finding_id_a, finding_id_b, relationship)
);


-- -----------------------------------------------------------------------------
-- traces: reachability analysis per confirmed finding.
-- -----------------------------------------------------------------------------
--
-- One per (finding, trace pass). Like validations, v1 has exactly one trace
-- per finding (UNIQUE constraint). The call_chain is stored as JSON because
-- it's read as a unit (the Report needs the whole chain to render) and never
-- queried element-by-element.

CREATE TABLE traces (
    id                  TEXT NOT NULL,                   -- ULID
    finding_id          TEXT NOT NULL,
    reachable           TEXT NOT NULL,                   -- 'reachable' | 'unreachable' | 'uncertain'
    entry_point_symbol  TEXT,                            -- required if reachable='reachable' (app-enforced)
    entry_point_id      TEXT,                            -- FK to entry_points if matched; NULL otherwise
    call_chain_json     TEXT NOT NULL,                   -- JSON array of CallChainStep
    rationale           TEXT NOT NULL,                   -- markdown
    agent_session_id    TEXT NOT NULL,
    created_at          TEXT NOT NULL,

    CONSTRAINT pk_traces PRIMARY KEY (id),
    CONSTRAINT fk_traces_finding_id_findings
        FOREIGN KEY (finding_id) REFERENCES findings(id) ON DELETE CASCADE,
    CONSTRAINT fk_traces_entry_point_id_entry_points
        FOREIGN KEY (entry_point_id) REFERENCES entry_points(id) ON DELETE SET NULL,
    CONSTRAINT fk_traces_agent_session_id_agent_sessions
        FOREIGN KEY (agent_session_id) REFERENCES agent_sessions(id) ON DELETE RESTRICT,
    CONSTRAINT uq_traces_finding_id UNIQUE (finding_id),
    CONSTRAINT ck_traces_reachable
        CHECK (reachable IN ('reachable', 'unreachable', 'uncertain')),
    CONSTRAINT ck_traces_call_chain_valid CHECK (json_valid(call_chain_json)),
    -- "reachable -> entry_point_symbol is non-null" check; entry_point_id may still be NULL
    -- if the symbol wasn't in the entry_points table (which would be unusual but possible).
    CONSTRAINT ck_traces_reachable_has_entry_point
        CHECK (reachable != 'reachable' OR entry_point_symbol IS NOT NULL)
);


-- -----------------------------------------------------------------------------
-- agent_sessions: one row per LLM session invocation.
-- -----------------------------------------------------------------------------
--
-- The audit log for every agent call FlossWing makes. Stages reference their
-- session here; findings.poc_result_json references compile_and_run sandbox
-- runs which AREN'T agent sessions (those go in sandbox_runs).
--
-- This is the table to query when "did the model refuse?" or "how much did
-- this run cost?" — the per-stage breakdown comes from grouping on `stage`.

CREATE TABLE agent_sessions (
    id                  TEXT NOT NULL,                   -- ULID
    run_id              TEXT NOT NULL,
    stage               TEXT NOT NULL,                   -- 'recon' | 'hunt' | 'validate' | 'gapfill' | 'dedupe' | 'trace'
    task_id             TEXT,                            -- hunt_tasks.id for hunt stage; NULL for others
    finding_id          TEXT,                            -- for validate/trace; NULL for others
    model               TEXT NOT NULL,                   -- e.g. 'claude-opus-4-7'
    system_prompt_hash  TEXT NOT NULL,                   -- sha256 of the system prompt, for prompt-version tracking
    input_tokens        INTEGER NOT NULL,
    output_tokens       INTEGER NOT NULL,
    cache_read_tokens   INTEGER NOT NULL DEFAULT 0,
    cache_write_tokens  INTEGER NOT NULL DEFAULT 0,
    cost_usd            REAL NOT NULL,                   -- computed at session-end from model pricing
    duration_ms         INTEGER NOT NULL,
    outcome             TEXT NOT NULL,                   -- see CHECK below
    refusal_text        TEXT,                            -- captured when outcome='refused'
    error_text          TEXT,                            -- captured when outcome='errored'
    tool_calls_count    INTEGER NOT NULL DEFAULT 0,
    started_at          TEXT NOT NULL,
    finished_at         TEXT NOT NULL,

    CONSTRAINT pk_agent_sessions PRIMARY KEY (id),
    CONSTRAINT fk_agent_sessions_run_id_runs
        FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
    -- task_id and finding_id NOT FK'd to keep this table append-only and
    -- robust against parent deletions; we treat agent_sessions as immutable audit log.
    CONSTRAINT ck_agent_sessions_stage
        CHECK (stage IN ('recon', 'hunt', 'validate', 'gapfill', 'dedupe', 'trace')),
    CONSTRAINT ck_agent_sessions_outcome
        CHECK (outcome IN ('completed', 'refused', 'budget_exceeded', 'timed_out', 'errored')),
    CONSTRAINT ck_agent_sessions_tokens
        CHECK (input_tokens >= 0 AND output_tokens >= 0 AND cache_read_tokens >= 0 AND cache_write_tokens >= 0),
    CONSTRAINT ck_agent_sessions_cost CHECK (cost_usd >= 0)
);

CREATE INDEX ix_agent_sessions_run_id ON agent_sessions(run_id);
CREATE INDEX ix_agent_sessions_run_id_stage ON agent_sessions(run_id, stage);
CREATE INDEX ix_agent_sessions_outcome ON agent_sessions(outcome);


-- -----------------------------------------------------------------------------
-- sandbox_runs: every compile_and_run invocation.
-- -----------------------------------------------------------------------------
--
-- Distinct from agent_sessions: an agent session may issue many tool calls,
-- some of which are compile_and_run. This table is the audit log for the
-- highest-risk tool — what code did we execute, with what args, against what
-- attack class, with what result. Useful for forensics if a sandbox escape
-- is ever suspected.
--
-- Source code stored as JSON array of SourceFile to preserve fidelity. PoCs
-- are small (Hunter-generated source files), so size isn't an issue.

CREATE TABLE sandbox_runs (
    id                  TEXT NOT NULL,                   -- ULID
    run_id              TEXT NOT NULL,
    agent_session_id    TEXT NOT NULL,
    attack_class        TEXT NOT NULL,
    language            TEXT NOT NULL,
    files_json          TEXT NOT NULL,                   -- JSON array of SourceFile
    build_command       TEXT,
    run_command         TEXT NOT NULL,
    args_json           TEXT NOT NULL DEFAULT '[]',      -- JSON array
    env_json            TEXT NOT NULL DEFAULT '{}',      -- JSON object (allowlist-filtered)
    network_requested   INTEGER NOT NULL,                -- 0 | 1
    network_granted     INTEGER NOT NULL,                -- 0 | 1; should equal `requested` unless policy denied
    timeout_seconds     INTEGER NOT NULL,
    sandbox_backend     TEXT NOT NULL,                   -- 'docker' | 'firejail'
    build_result_json   TEXT,                            -- JSON ExecResult, or NULL if no build
    run_result_json     TEXT NOT NULL,                   -- JSON ExecResult
    started_at          TEXT NOT NULL,
    finished_at         TEXT NOT NULL,

    CONSTRAINT pk_sandbox_runs PRIMARY KEY (id),
    CONSTRAINT fk_sandbox_runs_run_id_runs
        FOREIGN KEY (run_id) REFERENCES runs(id) ON DELETE CASCADE,
    CONSTRAINT fk_sandbox_runs_agent_session_id_agent_sessions
        FOREIGN KEY (agent_session_id) REFERENCES agent_sessions(id) ON DELETE CASCADE,
    CONSTRAINT ck_sandbox_runs_language
        CHECK (language IN ('c', 'cpp', 'rust', 'go', 'python', 'javascript', 'typescript', 'java')),
    CONSTRAINT ck_sandbox_runs_network
        CHECK (network_requested IN (0, 1) AND network_granted IN (0, 1)),
    CONSTRAINT ck_sandbox_runs_backend
        CHECK (sandbox_backend IN ('docker', 'firejail')),
    CONSTRAINT ck_sandbox_runs_files_valid CHECK (json_valid(files_json)),
    CONSTRAINT ck_sandbox_runs_args_valid CHECK (json_valid(args_json)),
    CONSTRAINT ck_sandbox_runs_env_valid CHECK (json_valid(env_json)),
    CONSTRAINT ck_sandbox_runs_build_result_valid
        CHECK (build_result_json IS NULL OR json_valid(build_result_json)),
    CONSTRAINT ck_sandbox_runs_run_result_valid CHECK (json_valid(run_result_json))
);

CREATE INDEX ix_sandbox_runs_run_id ON sandbox_runs(run_id);
CREATE INDEX ix_sandbox_runs_agent_session_id ON sandbox_runs(agent_session_id);


-- -----------------------------------------------------------------------------
-- alembic_version: managed by Alembic, included here for completeness.
-- -----------------------------------------------------------------------------
--
-- Alembic creates this automatically. Listed here so the CI schema-check
-- doesn't flag it as drift. Do not write migrations against this table.

CREATE TABLE alembic_version (
    version_num         VARCHAR(32) NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);


-- =============================================================================
-- Notes for implementers
-- =============================================================================
--
-- ON DELETE behavior summary:
--   - Deleting a run cascades to ~everything (findings, tasks, sessions, etc.)
--     This is intentional: a run is the unit of forensic interest, and
--     deleting it should leave no orphans.
--   - Deleting a finding cascades to its validations, traces, and the
--     dedupe_cluster where it's the primary. Findings linked as variants/
--     duplicates get their primary_finding_id set to NULL (SET NULL FK).
--   - agent_sessions referenced by validations/traces use ON DELETE RESTRICT
--     to preserve audit integrity. Run deletion cascades through the run_id
--     path before this triggers, so it's not normally blocking.
--
-- Performance assumptions:
--   - SQLite WAL mode is enabled at connection time (`PRAGMA journal_mode=WAL`)
--     for concurrent read access during scans.
--   - `PRAGMA synchronous=NORMAL` is acceptable; the state is reproducible from
--     the target repo if catastrophically lost mid-scan.
--   - Single-writer assumption holds: only the orchestrator writes; agents
--     write only via tool handlers which serialize through the orchestrator.
--
-- What's deliberately not here:
--   - No `users` table: single-user tool.
--   - No `projects` table: a run already knows its target_repo_path.
--   - No `prompts` table: prompts are version-controlled in flosswing/prompts/
--     and identified via system_prompt_hash on agent_sessions. If we want to
--     reproduce a scan, we check out the matching FlossWing version.
--   - No FTS tables: findings are reviewed in the report, not searched.
--     Could add FTS5 over findings.description in v2 if grep insufficient.
